[versions]
kotest = "5.9.1"

[libraries]
kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }

[bundles]
kotest = ["kotest-junit5", "kotest-core", "kotest-datatest"]
